### ISSUE TITLE
Mimic Mapbox Directions API

### ISSUE THREAD

**Issue by carocad** [n7a235/service.routing#11]
In order to use all the functionality from Mapbox in the mobile apps, it would be best if we could mimic the response from [Mapbox directions API](https://www.mapbox.com/api-documentation/#directions).

A few issues still remain regarding the possible use of Mapbox navigation library (for mobiles) currently in Beta.

**Comment by mehdisadeghi** [comment]
@carocad can you be more specific? Mapbox has _driving_, _driving_traffic_, _walking_ and _cycling_. The format for all of them are the same. The only differences that I see are use of `weight-length` instead of `weight_length` and the lack of `legs` that you have made a PR for it. Anything else?

**Comment by carocad** [comment]
@mehdisadeghi sure thing.
I separated this issue into two:
- mimicking the api
- mimicking the response

I am working on mimicking the response from mapbox but there are extra parameters that I will need in order to do that. Currently the most important would be `steps`. As for the profile right now we only support `walking`. I think it should also be part of the url parameters but it is definitely not a MUST.

So what I am referring here are the GET url parameters that is possible to include in the request to mapbox. Most of them are of no interest to us right now so I would leave up to you which ones you include. My only request right now would be the `steps` parameter since I would need it to decide whether we send turn-by-turn navigation or not.

Details: https://www.mapbox.com/api-documentation/#retrieve-directions

**Comment by mehdisadeghi** [comment]
@carocad `steps` aside there are other parameters: `alternatives, geometries, overview, radiuses, continue_straight, bearings, annotations, language`. I think the only relevant ones are `alternatives` and `radiuses`. What do you think?

**Comment by carocad** [comment]
@mehdisadeghi agree. Although I would also add `language`. Would maybe be useful in the near future

**Comment by mehdisadeghi** [comment]
@carocad I just realized that Mapbox's respones is not accurately documented. For example in [their docs](https://www.mapbox.com/api-documentation/?language=cURL#retrieve-directions) they describe `radiuses` to be some number greater than 0 or `unlimited`. However, their API returns an error message if a number larger than 50 is provided. Moreover it accepts empty strings as well as `unlimited`.

**Comment by carocad** [comment]
@mehdisadeghi I guess they dont have a full spec in place like ours to do such specific checks ;)

> Update: It appears in the error message that radiuses should be smaller than 50, but regardless the API accepts numbers larger than 50.

I am confused. So can you pass a number greater than 50 or not? and if you do, do you get an error saying that it shouldnt?

**Comment by mehdisadeghi** [comment]
> I am confused. So can you pass a number greater than 50 or not?

Yes, you can.

> and if you do, do you get an error saying that it shouldnt?

No, you don't.

See:

```
curl https://api.mapbox.com/directions/v5/mapbox/driving/
13.4301,52.5109;13.4265,52.5080;13.4194,52.5072
?radiuses=410;unlimited;100
&geometries=polyline
&access_token=TOKEN"

{
    "waypoints": [
        {
            "name": "Andreasstraße",
            "location": [
                13.430407,
                52.510853
            ]
        },
        {
            "name": "Köpenicker Straße",
            "location": [
                13.426579,
                52.508068
            ]
        },
        {
            "name": "",
            "location": [
                13.419695,
                52.507284
            ]
        }
    ],
    "routes": [
        {
            "legs": [
                {
                    "steps": [],
                    "weight": 159.6,
                    "distance": 510.3,
                    "summary": "",
                    "duration": 141.6
                },
                {
                    "steps": [],
                    "weight": 231.6,
                    "distance": 690.4,
                    "summary": "",
                    "duration": 135.7
                }
            ],
            "weight_name": "routability",
            "geometry": "y_o_Iac~pA|CjAhIdHvBzA\\p@TRgBhFoBtGc@fBdKxGsCbO`BdAa@|B",
            "weight": 391.2,
            "distance": 1200.7,
            "duration": 277.29999999999995
        }
    ],
    "code": "Ok"
}```

**Comment by carocad** [comment]
ah ok. Got it now, thanks for the explanation. Well you could report the issue if you want

It is our win anyway :)
