### ISSUE TITLE
transform speeds to meters / second

### ISSUE THREAD

**Issue by carocad** [n7a235/service.routing#15]
Currently the speeds used by the OSM edges in our service are defined in km/h. The problem is that the length and all other parameters are defined in meter or second. Therefore using km/h is wrong nevertheless I have been using it out of lack of priorities.

I think this could be an easy exercise for you. Execute a command in the repl that takes the OSM speeds and transforms them from km/h to meter/second

https://github.com/n7a235/service.routing/blob/directions/src/service/routing/osm.clj#L76

**Comment by mehdisadeghi** [comment]
Should we floor or ceil the converted numbers (and with how many decimal points) ?

**Comment by carocad** [comment]
oh no idea. I would just round it. We have the git history and links in case we want to rollback. For the time being we dont know how much will this affect the results so lets just go with gut feeling and learn from it ;)
