### ISSUE TITLE
Create  a Dockerfile

### ISSUE THREAD

**Issue by mehdisadeghi** [n7a235/service.routing#18]

**Comment by carocad** [comment]
@mehdisadeghi can you add this to a specific project?

That way we can better decide how to prioritize things

**Comment by mehdisadeghi** [comment]
@carocad Shall we create a new project in this repository or should I modify org level defined projects?

**Comment by carocad** [comment]
@mehdi well that depends on you. If you think that this can be done fast and without much trouble then I would just add it to the alpha project. If you think it would definitely take more time then I would create a new "beta" project and put it there.

If you decide to add it to the alpha or first prototype project, you can change here in the right side ;)
