### ISSUE TITLE
spec definitions broken

### ISSUE THREAD

**Issue by carocad** [n7a235/service.routing#23]
Probably the latest merge broke our specs definitions. If you check the file there are lots of duplicated definitions like waypoint objects and routes.

https://github.com/n7a235/service.routing/blob/master/src/service/routing/spec.clj#L32

**Comment by mehdisadeghi** [comment]
Oh bad. I'll fix it as soon as I get back home.

**Comment by carocad** [comment]
btw not sure if you know this little trick of github but if you write `fixes` or `closes` and the number of the ticket in a commit or pr, then github automatically closes the issue after the pr is merged ;)

**Comment by mehdisadeghi** [comment]
Ah yes, I thought `Fix #` will work!
