### ISSUE TITLE
introduce components for future extensibility

### ISSUE THREAD

**Issue by carocad** [n7a235/service.routing#44]
An interesting framework for developing apps in Clojure is  `Components`.

It is about managing the lifecycle of the different components of an app. I think it would be good for us to develop our app using that pattern given that we already have the bases for it i.e. fake graph/network.

A downside of this approach is that `lein ring` doesnt work with this way of doing things as ring only allows using a single static handler and component is precisely about replacing/injecting those at runtime.

CC: @mehdisadeghi 

References:
- [conference video](https://www.youtube.com/watch?v=13cmHf_kt-Q)
- [compojure + component](https://github.com/metosin/compojure-api/wiki/Component-integration)
- [lein-ring problem](https://github.com/weavejester/lein-ring/issues/189)

**Comment by mehdisadeghi** [comment]
I watched the video and it looks more like a way of thinking rather than a framework to me. The presentation was good, however the library in question has the author as the only contributor. I'm in principle a little bit hesitant using such dependencies. It reminds me some web frameworks and application frameworks that provide means of defining subsystems, each in a different way.

**Comment by carocad** [comment]
yeah I guess you are right about the way of thinking thing. I guess it is simply a way to enforce this way of thinking ;)

You can of course bypass it and put state into separate parts of the app but then you loose the benefits of the framework.

As for the single contributor thing, I actually didnt notice. It is a bit weird though that he is the only contributor. What I did was check the literature on Clojure about how to represent state in a Clojure app and this one was the most appealing one and also one of the most known one. The other one that I know of is [mount](https://github.com/tolitius/mount).

I didnt like that one that much though since it requires splitting the state of the app into separate mutable global parts which defeats the purpose of functional programing and pure functions.

Nevertheless it could be that I am interpreting it wrong since this is my first time building a big Clojure app (previously only libs). For the time being I think that we just need to make a decision about how to handle state in our app but since we dont have the experience yet to judge that I went with the language standard
